/**
 * Generated by njsgen
 */

/*NJSGEN INCLUDE_HEAD BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN INCLUDE_HEAD END*/
#include <string.h>
#include <stdlib.h>
#include <ratjs.h>
/*NJSGEN INCLUDE_TAIL BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN INCLUDE_TAIL END*/

#define NJS_NATIVE_FUNC(n)\
    RJS_Result n (RJS_Runtime *njs_rt, RJS_Value *njs_func, RJS_Value *njs_thiz, RJS_Value *njs_args, size_t njs_argc, RJS_Value *njs_nt, RJS_Value *njs_rv)

/*NJSGEN DECL BEGIN*/

#define NUM_MACRO_0  0x19781009
#define NUM_MACRO_PI 3.1415926

typedef enum {
    MY_ENUM0_V0,
    MY_ENUM0_V1,
    MY_ENUM0_V2
} MyEnum0;

enum MyEnum1 {
    MY_ENUM1_V2 = 2,
    MY_ENUM1_V3,
    MY_ENUM1_V4
};

typedef struct {
    uint8_t  u8;
    uint16_t u16;
    uint32_t u32;
    uint64_t u64;
} MyStruct1;

typedef struct {
    char      s[32];
    MyStruct1 s1;
    MyStruct1 s1a[4];
    uint8_t   u8a[32];
} MyStruct2;

typedef union {
    uint8_t  u8;
    uint16_t u16;
    uint32_t u32;
    uint64_t u64;
} MyUnion;

typedef int (*MyFuncType) (int a);
typedef int (*MyFuncType1) (int a, int *b, MyStruct1 *c, int *d);

static int iv = 1314250;
static MyStruct1 sv;
static const MyStruct1 csv = {
    u32: 1234567
};

static int func(int v)
{
    return v + 100;
}

static MyFuncType fnv = func;

static int
MyFunc0 (int a)
{
    return -a;
}

static int
MyFunc1 (const char *a)
{
    return a ? strlen(a) : 0;
}

static const char*
MyFunc2 ()
{
    return "test!";
}

static void
MyFunc3 (int *a)
{
    *a = 1900;
}

static int
MyFunc4 (int *a)
{
    int r = *a;

    *a = -r;

    return r;
}

static void
MyFunc5 (MyStruct1 *a)
{
    a->u32 = ~a->u32;
}

static void
MyFunc6 (MyStruct1 a[2])
{
    a[0].u32 = 1234;
    a[1].u32 = 5678;
}

static void
MyFunc7 (uint16_t *a, int b)
{
    int i;

    for (i = 0; i < b; i ++)
        a[i] = i;
}

static int
MyFunc8 (MyFuncType f, int a)
{
    return -f(a);
}

static int
MyFunc9 (MyFuncType1 f)
{
    int r, b;
    MyStruct1 c;
    int d[256];
    int i;

    for (i = 0; i < 256; i ++)
        d[i] = i;

    c.u32 = 987654321;

    r = f(100, &b, &c, d);

    return r + b;
}

/*NJSGEN DECL END*/

/*Local export symbols.*/
static const RJS_ModuleExportDesc
njs_local_exports[] = {
    {NULL, NULL, "NUM_MACRO_0", "NUM_MACRO_0"},
    {NULL, NULL, "NUM_MACRO_PI", "NUM_MACRO_PI"},
    {NULL, NULL, "MY_ENUM0_V0", "MY_ENUM0_V0"},
    {NULL, NULL, "MY_ENUM0_V1", "MY_ENUM0_V1"},
    {NULL, NULL, "MY_ENUM0_V2", "MY_ENUM0_V2"},
    {NULL, NULL, "MY_ENUM1_V2", "MY_ENUM1_V2"},
    {NULL, NULL, "MY_ENUM1_V3", "MY_ENUM1_V3"},
    {NULL, NULL, "MY_ENUM1_V4", "MY_ENUM1_V4"},
    {NULL, NULL, "MyStruct1", "MyStruct1"},
    {NULL, NULL, "MyStruct2", "MyStruct2"},
    {NULL, NULL, "MyUnion", "MyUnion"},
    {NULL, NULL, "$", "$"},
    {NULL, NULL, "MyFuncType", "MyFuncType"},
    {NULL, NULL, "MyFuncType1", "MyFuncType1"},
    {NULL, NULL, "MyFunc0", "MyFunc0"},
    {NULL, NULL, "MyFunc1", "MyFunc1"},
    {NULL, NULL, "MyFunc2", "MyFunc2"},
    {NULL, NULL, "MyFunc3", "MyFunc3"},
    {NULL, NULL, "MyFunc4", "MyFunc4"},
    {NULL, NULL, "MyFunc5", "MyFunc5"},
    {NULL, NULL, "MyFunc6", "MyFunc6"},
    {NULL, NULL, "MyFunc7", "MyFunc7"},
    {NULL, NULL, "MyFunc8", "MyFunc8"},
    {NULL, NULL, "MyFunc9", "MyFunc9"},
/*NJSGEN EXPORT_TABLE_DECL BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN EXPORT_TABLE_DECL END*/
    {NULL, NULL, NULL, NULL}
};

/*NJS module data.*/
typedef struct {
    RJS_CType *ctype_MyStruct1;
    RJS_CType *ctype_MyStruct2;
    RJS_CType *ctype_MyUnion;
    RJS_CType *ctype_MyFuncType;
    RJS_CType *ctype_MyFuncType1;
    RJS_Value str_b;
    RJS_Value str_return;
    RJS_Value str_a;
    RJS_PropertyName pn_b;
    RJS_PropertyName pn_return;
    RJS_PropertyName pn_a;
/*NJSGEN MODULE_DATA_DECL BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_DECL END*/
} NJS_ModuleData;

/*Scan the referenced things in the module data.*/
static void
njs_module_data_scan (RJS_Runtime *njs_rt, void *njs_p)
{
    NJS_ModuleData *njs_md = njs_p;

    njs_md = njs_md;
    rjs_gc_scan_value(njs_rt, &njs_md->str_b);
    rjs_gc_scan_value(njs_rt, &njs_md->str_return);
    rjs_gc_scan_value(njs_rt, &njs_md->str_a);

/*NJSGEN MODULE_DATA_SCAN BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_SCAN END*/
}

/*Free the module data.*/
static void
njs_module_data_free (RJS_Runtime *njs_rt, void *njs_p)
{
    NJS_ModuleData *njs_md = njs_p;

    rjs_property_name_deinit(njs_rt, &njs_md->pn_b);
    rjs_property_name_deinit(njs_rt, &njs_md->pn_return);
    rjs_property_name_deinit(njs_rt, &njs_md->pn_a);

/*NJSGEN MODULE_DATA_FREE BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_FREE END*/

    free(njs_md);
}

/*NJSGEN FUNC_HEAD BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN FUNC_HEAD END*/

/*Constructor of "MyStruct1"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    MyStruct1 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the MyStruct1 buffer.*/
    njs_cptr = malloc(sizeof(MyStruct1) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(MyStruct1));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the MyStruct1.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct1.u8"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u8_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u8".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u8);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct1.u8"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u8_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;
    RJS_Number njs_u8_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u8".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u8_num)) == RJS_ERR)
        goto end;
    njs_cptr->u8 = njs_u8_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct1.u16"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u16_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u16".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u16);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct1.u16"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u16_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;
    RJS_Number njs_u16_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u16".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u16_num)) == RJS_ERR)
        goto end;
    njs_cptr->u16 = njs_u16_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct1.u32"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u32_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u32".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u32);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct1.u32"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u32_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;
    RJS_Number njs_u32_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u32".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u32_num)) == RJS_ERR)
        goto end;
    njs_cptr->u32 = njs_u32_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct1.u64"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u64_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u64".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u64);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct1.u64"*/
static NJS_NATIVE_FUNC(njs_MyStruct1_u64_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1 *njs_cptr;
    RJS_Number njs_u64_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct1 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u64".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u64_num)) == RJS_ERR)
        goto end;
    njs_cptr->u64 = njs_u64_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "MyStruct2"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    MyStruct2 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the MyStruct2 buffer.*/
    njs_cptr = malloc(sizeof(MyStruct2) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(MyStruct2));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct2, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the MyStruct2.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct2.s"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "s".*/
    if ((njs_r = rjs_string_from_enc_chars(njs_rt, njs_rv, njs_cptr->s, -1, NULL)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct2.s"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;
    RJS_Value *njs_s_str = rjs_value_stack_push(njs_rt);
    const char *njs_s_cstr;
    RJS_CharBuffer njs_s_cb;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    rjs_char_buffer_init(njs_rt, &njs_s_cb);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "s".*/
    if ((njs_r = rjs_to_string(njs_rt, njs_arg, njs_s_str)) == RJS_ERR)
        goto end;
    if (!(njs_s_cstr = rjs_string_to_enc_chars(njs_rt, njs_s_str, &njs_s_cb, NULL))) {
        njs_r = RJS_ERR;
        goto end;
    }
    if (snprintf(njs_cptr->s, sizeof(njs_cptr->s), "%s", njs_s_cstr) >= sizeof(njs_cptr->s)) {
        njs_r = rjs_throw_range_error(njs_rt, "input string is too long");
        goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_char_buffer_deinit(njs_rt, &njs_s_cb);
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct2.u8a"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_u8a_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u8a".*/
    if ((njs_r = rjs_create_c_typed_array(njs_rt, RJS_ARRAY_ELEMENT_UINT8, njs_cptr->u8a, RJS_N_ELEM(njs_cptr->u8a), njs_rv)) == RJS_ERR) {
        goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct2.u8a"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_u8a_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;
    uint8_t *njs_u8a_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u8a".*/
    if (!(njs_u8a_cptr = rjs_get_c_ptr(njs_rt, NULL, RJS_ARRAY_ELEMENT_UINT8, njs_arg))) {
        njs_r = rjs_throw_type_error(njs_rt, "typed array type mismatch");
        goto end;
    }

    /*Check the length of "u8a".*/
    if (rjs_get_c_array_length(njs_rt, njs_arg) < RJS_N_ELEM(njs_cptr->u8a)) {
        njs_r = rjs_throw_range_error(njs_rt, "the typed array length is less than expected lenth");;
        goto end;
    }

    /*Copy "u8a".*/
    RJS_ELEM_CPY(njs_cptr->u8a, njs_u8a_cptr, RJS_N_ELEM(njs_cptr->u8a));
    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct2.s1a"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s1a_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "s1a".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, (void*)njs_cptr->s1a, RJS_CPTR_TYPE_ARRAY, RJS_N_ELEM(njs_cptr->s1a), 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct2.s1a"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s1a_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;
    MyStruct1 *njs_s1a_cptr;
    size_t njs_s1a_len;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "s1a".*/
    if (!(njs_s1a_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_ARRAY, njs_arg))) {
        njs_r = RJS_ERR;
        goto end;
    }
    njs_s1a_len = rjs_get_c_array_length(njs_rt, njs_arg);
    RJS_ELEM_CPY(njs_cptr->s1a, njs_s1a_cptr, RJS_MIN(njs_s1a_len, RJS_N_ELEM(njs_cptr->s1a)));

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyStruct2.s1"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s1_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "s1".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, (void*)&njs_cptr->s1, RJS_CPTR_TYPE_VALUE, 1, 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyStruct2.s1"*/
static NJS_NATIVE_FUNC(njs_MyStruct2_s1_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct2 *njs_cptr;
    MyStruct1* njs_s1_cptr;
    RJS_Value *njs_s1_cptrv = rjs_value_stack_push(njs_rt);

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyStruct2 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct2, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "s1".*/
    if (rjs_is_c_ptr(njs_rt, njs_arg)) {
        if (!(njs_s1_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }
        njs_cptr->s1 = *njs_s1_cptr;
    } else {
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, &njs_cptr->s1, RJS_CPTR_TYPE_VALUE, 1, 0, njs_s1_cptrv)) == RJS_ERR)
            goto end;
        if ((njs_r = rjs_object_assign(njs_rt, njs_s1_cptrv, njs_arg)) == RJS_ERR)
            goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "MyUnion"*/
static NJS_NATIVE_FUNC(njs_MyUnion_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    MyUnion *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the MyUnion buffer.*/
    njs_cptr = malloc(sizeof(MyUnion) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(MyUnion));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyUnion, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the MyUnion.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyUnion.u8"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u8_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u8".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u8);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyUnion.u8"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u8_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;
    RJS_Number njs_u8_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u8".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u8_num)) == RJS_ERR)
        goto end;
    njs_cptr->u8 = njs_u8_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyUnion.u16"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u16_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u16".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u16);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyUnion.u16"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u16_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;
    RJS_Number njs_u16_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u16".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u16_num)) == RJS_ERR)
        goto end;
    njs_cptr->u16 = njs_u16_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyUnion.u32"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u32_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u32".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u32);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyUnion.u32"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u32_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;
    RJS_Number njs_u32_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u32".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u32_num)) == RJS_ERR)
        goto end;
    njs_cptr->u32 = njs_u32_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "MyUnion.u64"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u64_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "u64".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->u64);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "MyUnion.u64"*/
static NJS_NATIVE_FUNC(njs_MyUnion_u64_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyUnion *njs_cptr;
    RJS_Number njs_u64_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the MyUnion pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyUnion, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "u64".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_u64_num)) == RJS_ERR)
        goto end;
    njs_cptr->u64 = njs_u64_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "$.iv"*/
static NJS_NATIVE_FUNC(njs_iv_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;

    /*Get "iv".*/
    rjs_value_set_number(njs_rt, njs_rv, iv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "$.iv"*/
static NJS_NATIVE_FUNC(njs_iv_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_iv_num;

    /*Set "iv".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_iv_num)) == RJS_ERR)
        goto end;
    iv = njs_iv_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "$.sv"*/
static NJS_NATIVE_FUNC(njs_sv_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get "sv".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, (void*)&sv, RJS_CPTR_TYPE_VALUE, 1, 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "$.sv"*/
static NJS_NATIVE_FUNC(njs_sv_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    MyStruct1* njs_sv_cptr;
    RJS_Value *njs_sv_cptrv = rjs_value_stack_push(njs_rt);

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Set "sv".*/
    if (rjs_is_c_ptr(njs_rt, njs_arg)) {
        if (!(njs_sv_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }
        sv = *njs_sv_cptr;
    } else {
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, &sv, RJS_CPTR_TYPE_VALUE, 1, 0, njs_sv_cptrv)) == RJS_ERR)
            goto end;
        if ((njs_r = rjs_object_assign(njs_rt, njs_sv_cptrv, njs_arg)) == RJS_ERR)
            goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "$.csv"*/
static NJS_NATIVE_FUNC(njs_csv_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get "csv".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, (void*)&csv, RJS_CPTR_TYPE_VALUE, 1, 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "$.fnv"*/
static NJS_NATIVE_FUNC(njs_fnv_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get "fnv".*/
    if (fnv == NULL)
        rjs_value_set_null(njs_rt, njs_rv);
    else if ((njs_r = rjs_create_c_func_ptr(njs_rt, njs_md->ctype_MyFuncType, fnv, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*"MyFuncType" js -> ffi.*/
static RJS_Result
njs_MyFuncType_js2ffi (RJS_Runtime *njs_rt, ffi_cif *njs_cif, RJS_Value *njs_args, size_t njs_argc, void *njs_cf, RJS_Value *njs_rv, void *njs_data)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    void *njs_rp;
    void *njs_argp[njs_cif->nargs];
    int njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_a_num;
    int njs_ret;

    /*Convert input parameter "a".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_a, &njs_a_num)) == RJS_ERR)
        goto end;
    njs_arg_a = njs_a_num;
    /*Store arguments to ffi arguments pointer array.*/
    njs_argp[0] = &njs_arg_a;
    njs_rp = &njs_ret;

    /*Call "MyFuncType".*/
    ffi_call(njs_cif, njs_cf, njs_rp, njs_argp);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*"MyFuncType" ffi -> js.*/
static RJS_Result
njs_MyFuncType_ffi2js (RJS_Runtime *njs_rt, void **njs_argp, int njs_argc, RJS_Value *njs_fn, void *njs_rp, void *njs_data)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_rv = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_arg;
    int njs_arg_a;
    RJS_Value *njs_args = rjs_value_stack_push_n(njs_rt, 1);
    RJS_Number njs_return_num;

    /*Get parameter "a".*/
    njs_arg_a = *(int*)njs_argp[0];
    /*Convert parameter "a".*/
    njs_arg = rjs_value_buffer_item(njs_rt, njs_args, 0);
    rjs_value_set_number(njs_rt, njs_arg, njs_arg_a);

    /*Call the JS function.*/
    if ((njs_r = rjs_call(njs_rt, njs_fn, rjs_v_undefined(njs_rt), njs_args, 1, njs_rv)) == RJS_ERR)
        goto end;

    /*Convert return value.*/
    if ((njs_r = rjs_to_number(njs_rt, njs_rv, &njs_return_num)) == RJS_ERR)
        goto end;
    *(int*)njs_rp = njs_return_num;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "MyFuncType"*/
static NJS_NATIVE_FUNC(njs_MyFuncType_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_C_WRAPPER;
    void *njs_cptr;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;

        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;

        /*Allocate the MyFuncType buffer.*/
        njs_cptr = malloc(sizeof(void*) * njs_nitem);
        if (!njs_cptr) {
            njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
            goto end;
        }
        memset(njs_cptr, 0, njs_nitem * sizeof(void*));

        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;

        /*Create the C pointer object.*/
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyFuncType, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
            goto end;
    } else {
        if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyFuncType, RJS_CPTR_TYPE_C_FUNC, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }

        rjs_value_copy(njs_rt, njs_rv, njs_arg);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Add function type "MyFuncType".*/
static void
njs_add_func_type_MyFuncType (RJS_Runtime *njs_rt, RJS_Value *njs_mod, RJS_CType **njs_pctype, void *njs_data)
{
    size_t     njs_top  = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_constr = rjs_value_stack_push(njs_rt);
    RJS_Realm *njs_realm = rjs_realm_current(njs_rt);
    ffi_type  *njs_rtype;
    ffi_type  *njs_atypes[1];

    rjs_string_from_chars(njs_rt, njs_name, "MyFuncType", -1);
    njs_atypes[0] = &ffi_type_sint;
    njs_rtype = &ffi_type_sint;
    rjs_create_c_func_type(njs_rt, njs_name, 1, njs_rtype, njs_atypes, njs_MyFuncType_js2ffi, njs_MyFuncType_ffi2js, njs_data, njs_pctype);

    rjs_ordinary_object_create(njs_rt, rjs_realm_function_prototype(njs_realm), njs_proto);
    rjs_create_builtin_function(njs_rt, njs_mod, njs_MyFuncType_constructor, 1, njs_name, NULL, NULL, NULL, njs_constr);
    rjs_make_constructor(njs_rt, njs_constr, RJS_FALSE, njs_proto);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_constr);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*"MyFuncType1" js -> ffi.*/
static RJS_Result
njs_MyFuncType1_js2ffi (RJS_Runtime *njs_rt, ffi_cif *njs_cif, RJS_Value *njs_args, size_t njs_argc, void *njs_cf, RJS_Value *njs_rv, void *njs_data)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    void *njs_rp;
    void *njs_argp[njs_cif->nargs];
    int njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_a_num;
    int* njs_arg_b;
    int njs_arg_d_b;
    MyStruct1* njs_arg_c;
    RJS_Value *njs_arg_v_c = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    NJS_ModuleData *njs_md = njs_data;
    int* njs_arg_d;
    RJS_Value *njs_arg_v_d = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    int njs_ret;
    RJS_Value *njs_ret_p = rjs_value_stack_push(njs_rt);

    njs_arg_b = &njs_arg_d_b;

    /*Convert input parameter "a".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_a, &njs_a_num)) == RJS_ERR)
        goto end;
    njs_arg_a = njs_a_num;
    /*Convert input parameter "c".*/
    if (!(njs_arg_c = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_arg_v_c))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "d".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_d) || rjs_value_is_undefined(njs_rt, njs_arg_v_d)) {
        njs_arg_d = NULL;
    } else if (!(njs_arg_d = rjs_get_c_ptr(njs_rt, NULL, RJS_ARRAY_ELEMENT_INT, njs_arg_v_d))) {
        njs_r = rjs_throw_type_error(njs_rt, "typed array type mismatch");
        goto end;
    }
    /*Store arguments to ffi arguments pointer array.*/
    njs_argp[0] = &njs_arg_a;
    njs_argp[1] = &njs_arg_b;
    njs_argp[2] = &njs_arg_c;
    njs_argp[3] = &njs_arg_d;
    njs_rp = &njs_ret;

    /*Check the length of "d".*/
    if (rjs_get_c_array_length(njs_rt, njs_arg_v_d) < 256) {
        njs_r = rjs_throw_range_error(njs_rt, "the typed array length is less than expected lenth");;
        goto end;
    }

    /*Call "MyFuncType1".*/
    ffi_call(njs_cif, njs_cf, njs_rp, njs_argp);
    /*Create return object.*/
    rjs_ordinary_object_create(njs_rt, NULL, njs_rv);

    /*Convert the output parameter "b".*/
    rjs_value_set_number(njs_rt, njs_ret_p, njs_arg_d_b);
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_b, njs_ret_p);
    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_ret_p, njs_ret);
    }
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_return, njs_ret_p);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*"MyFuncType1" ffi -> js.*/
static RJS_Result
njs_MyFuncType1_ffi2js (RJS_Runtime *njs_rt, void **njs_argp, int njs_argc, RJS_Value *njs_fn, void *njs_rp, void *njs_data)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_rv = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_arg;
    int njs_arg_a;
    MyStruct1* njs_arg_c;
    int* njs_arg_d;
    RJS_Value *njs_ret_p = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md = njs_data;
    RJS_Number njs_b_num;
    RJS_Value *njs_args = rjs_value_stack_push_n(njs_rt, 3);
    RJS_Number njs_return_num;

    /*Get parameter "a".*/
    njs_arg_a = *(int*)njs_argp[0];
    /*Get parameter "c".*/
    njs_arg_c = *(MyStruct1**)njs_argp[2];
    /*Get parameter "d".*/
    njs_arg_d = *(int**)njs_argp[3];
    /*Convert parameter "a".*/
    njs_arg = rjs_value_buffer_item(njs_rt, njs_args, 0);
    rjs_value_set_number(njs_rt, njs_arg, njs_arg_a);
    /*Convert parameter "c".*/
    njs_arg = rjs_value_buffer_item(njs_rt, njs_args, 1);
    if (njs_arg_c == NULL) {
        rjs_value_set_null(njs_rt, njs_arg);
    } else if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyStruct1, (void*)njs_arg_c, RJS_CPTR_TYPE_VALUE, 1, 0, njs_arg)) == RJS_ERR) {
        goto end;
    }
    /*Convert parameter "d".*/
    njs_arg = rjs_value_buffer_item(njs_rt, njs_args, 2);
    if (njs_arg_d == NULL) {
        rjs_value_set_null(njs_rt, njs_arg);
    } else if ((njs_r = rjs_create_c_typed_array(njs_rt, RJS_ARRAY_ELEMENT_INT, njs_arg_d, 256, njs_arg)) == RJS_ERR) {
        goto end;
    }

    /*Call the JS function.*/
    if ((njs_r = rjs_call(njs_rt, njs_fn, rjs_v_undefined(njs_rt), njs_args, 3, njs_rv)) == RJS_ERR)
        goto end;

    /*Convert output value of "b".*/
    if ((njs_r = rjs_get_v(njs_rt, njs_rv, &njs_md->pn_b, njs_ret_p)) == RJS_ERR)
        goto end;
    if ((njs_r = rjs_to_number(njs_rt, njs_ret_p, &njs_b_num)) == RJS_ERR)
        goto end;
    **(int**)njs_argp[1] = njs_b_num;
    /*Convert return value.*/
    if ((njs_r = rjs_get_v(njs_rt, njs_rv, &njs_md->pn_return, njs_ret_p)) == RJS_ERR)
        goto end;
    if ((njs_r = rjs_to_number(njs_rt, njs_ret_p, &njs_return_num)) == RJS_ERR)
        goto end;
    *(int*)njs_rp = njs_return_num;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "MyFuncType1"*/
static NJS_NATIVE_FUNC(njs_MyFuncType1_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_C_WRAPPER;
    void *njs_cptr;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;

        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;

        /*Allocate the MyFuncType1 buffer.*/
        njs_cptr = malloc(sizeof(void*) * njs_nitem);
        if (!njs_cptr) {
            njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
            goto end;
        }
        memset(njs_cptr, 0, njs_nitem * sizeof(void*));

        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;

        /*Create the C pointer object.*/
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_MyFuncType1, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
            goto end;
    } else {
        if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyFuncType1, RJS_CPTR_TYPE_C_FUNC, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }

        rjs_value_copy(njs_rt, njs_rv, njs_arg);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Add function type "MyFuncType1".*/
static void
njs_add_func_type_MyFuncType1 (RJS_Runtime *njs_rt, RJS_Value *njs_mod, RJS_CType **njs_pctype, void *njs_data)
{
    size_t     njs_top  = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_constr = rjs_value_stack_push(njs_rt);
    RJS_Realm *njs_realm = rjs_realm_current(njs_rt);
    ffi_type  *njs_rtype;
    ffi_type  *njs_atypes[4];

    rjs_string_from_chars(njs_rt, njs_name, "MyFuncType1", -1);
    njs_atypes[0] = &ffi_type_sint;
    njs_atypes[1] = &ffi_type_pointer;
    njs_atypes[2] = &ffi_type_pointer;
    njs_atypes[3] = &ffi_type_pointer;
    njs_rtype = &ffi_type_sint;
    rjs_create_c_func_type(njs_rt, njs_name, 4, njs_rtype, njs_atypes, njs_MyFuncType1_js2ffi, njs_MyFuncType1_ffi2js, njs_data, njs_pctype);

    rjs_ordinary_object_create(njs_rt, rjs_realm_function_prototype(njs_realm), njs_proto);
    rjs_create_builtin_function(njs_rt, njs_mod, njs_MyFuncType1_constructor, 1, njs_name, NULL, NULL, NULL, njs_constr);
    rjs_make_constructor(njs_rt, njs_constr, RJS_FALSE, njs_proto);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_constr);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Wrapper of "MyFunc0"*/
static NJS_NATIVE_FUNC(njs_MyFunc0_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_a_num;
    int njs_ret;

    /*Convert input parameter "a".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_a, &njs_a_num)) == RJS_ERR)
        goto end;
    njs_arg_a = njs_a_num;

    /*Call "MyFunc0".*/
    njs_ret = MyFunc0(njs_arg_a);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc1"*/
static NJS_NATIVE_FUNC(njs_MyFunc1_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    const char* njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_a_str = rjs_value_stack_push(njs_rt);
    RJS_CharBuffer njs_a_cb;
    int njs_ret;

    rjs_char_buffer_init(njs_rt, &njs_a_cb);

    /*Convert input parameter "a".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_a) || rjs_value_is_undefined(njs_rt, njs_arg_v_a)) {
        njs_arg_a = NULL;
    } else {
        if ((njs_r = rjs_to_string(njs_rt, njs_arg_v_a, njs_a_str)) == RJS_ERR)
            goto end;
        if (!(njs_arg_a = rjs_string_to_enc_chars(njs_rt, njs_a_str, &njs_a_cb, NULL))) {
            njs_r = RJS_ERR;
            goto end;
        }
    }

    /*Call "MyFunc1".*/
    njs_ret = MyFunc1(njs_arg_a);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_char_buffer_deinit(njs_rt, &njs_a_cb);
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc2"*/
static NJS_NATIVE_FUNC(njs_MyFunc2_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    const char* njs_ret;

    /*Call "MyFunc2".*/
    njs_ret = MyFunc2();

    /*Convert the return value.*/
    {
    if ((njs_r = rjs_string_from_enc_chars(njs_rt, njs_rv, njs_ret, -1, NULL)) == RJS_ERR)
        goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc3"*/
static NJS_NATIVE_FUNC(njs_MyFunc3_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int* njs_arg_a;
    int njs_arg_d_a;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_ret_p = rjs_value_stack_push(njs_rt);

    njs_arg_a = &njs_arg_d_a;
    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Call "MyFunc3".*/
    MyFunc3(njs_arg_a);
    /*Create return object.*/
    rjs_ordinary_object_create(njs_rt, NULL, njs_rv);

    /*Convert the output parameter "a".*/
    rjs_value_set_number(njs_rt, njs_ret_p, njs_arg_d_a);
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_a, njs_ret_p);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc4"*/
static NJS_NATIVE_FUNC(njs_MyFunc4_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int* njs_arg_a;
    int njs_arg_d_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_a_num;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    int njs_ret;
    RJS_Value *njs_ret_p = rjs_value_stack_push(njs_rt);

    njs_arg_a = &njs_arg_d_a;
    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "a".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_a, &njs_a_num)) == RJS_ERR)
        goto end;
    njs_arg_d_a = njs_a_num;

    /*Call "MyFunc4".*/
    njs_ret = MyFunc4(njs_arg_a);
    /*Create return object.*/
    rjs_ordinary_object_create(njs_rt, NULL, njs_rv);

    /*Convert the output parameter "a".*/
    rjs_value_set_number(njs_rt, njs_ret_p, njs_arg_d_a);
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_a, njs_ret_p);
    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_ret_p, njs_ret);
    }
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_return, njs_ret_p);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc5"*/
static NJS_NATIVE_FUNC(njs_MyFunc5_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    MyStruct1* njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "a".*/
    if (!(njs_arg_a = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_VALUE, njs_arg_v_a))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Call "MyFunc5".*/
    MyFunc5(njs_arg_a);

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc6"*/
static NJS_NATIVE_FUNC(njs_MyFunc6_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    MyStruct1* njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "a".*/
    if (!(njs_arg_a = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyStruct1, RJS_CPTR_TYPE_ARRAY, njs_arg_v_a))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Check the length of "a".*/
    if (rjs_get_c_array_length(njs_rt, njs_arg_v_a) < 2) {
        njs_r = rjs_throw_range_error(njs_rt, "the C array length is less than expected lenth");;
        goto end;
    }

    /*Call "MyFunc6".*/
    MyFunc6(njs_arg_a);

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc7"*/
static NJS_NATIVE_FUNC(njs_MyFunc7_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    uint16_t* njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    int njs_arg_b;
    RJS_Value *njs_arg_v_b = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Number njs_b_num;

    /*Convert input parameter "a".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_a) || rjs_value_is_undefined(njs_rt, njs_arg_v_a)) {
        njs_arg_a = NULL;
    } else if (!(njs_arg_a = rjs_get_c_ptr(njs_rt, NULL, RJS_ARRAY_ELEMENT_UINT16, njs_arg_v_a))) {
        njs_r = rjs_throw_type_error(njs_rt, "typed array type mismatch");
        goto end;
    }
    /*Convert input parameter "b".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_b, &njs_b_num)) == RJS_ERR)
        goto end;
    njs_arg_b = njs_b_num;

    /*Check the length of "a".*/
    if (rjs_get_c_array_length(njs_rt, njs_arg_v_a) < njs_arg_b) {
        njs_r = rjs_throw_range_error(njs_rt, "the typed array length is less than expected lenth");;
        goto end;
    }

    /*Call "MyFunc7".*/
    MyFunc7(njs_arg_a, njs_arg_b);

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc8"*/
static NJS_NATIVE_FUNC(njs_MyFunc8_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    MyFuncType njs_arg_f;
    RJS_Value *njs_arg_v_f = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    int njs_arg_a;
    RJS_Value *njs_arg_v_a = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Number njs_a_num;
    int njs_ret;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "f".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_f) || rjs_value_is_undefined(njs_rt, njs_arg_v_f))
        njs_arg_f = NULL;
    else if (!(njs_arg_f = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyFuncType, RJS_CPTR_TYPE_C_FUNC, njs_arg_v_f))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "a".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_a, &njs_a_num)) == RJS_ERR)
        goto end;
    njs_arg_a = njs_a_num;

    /*Call "MyFunc8".*/
    njs_ret = MyFunc8(njs_arg_f, njs_arg_a);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "MyFunc9"*/
static NJS_NATIVE_FUNC(njs_MyFunc9_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    MyFuncType1 njs_arg_f;
    RJS_Value *njs_arg_v_f = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    int njs_ret;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "f".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_f) || rjs_value_is_undefined(njs_rt, njs_arg_v_f))
        njs_arg_f = NULL;
    else if (!(njs_arg_f = rjs_get_c_ptr(njs_rt, njs_md->ctype_MyFuncType1, RJS_CPTR_TYPE_C_FUNC, njs_arg_v_f))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Call "MyFunc9".*/
    njs_ret = MyFunc9(njs_arg_f);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*NJSGEN FUNC_TAIL BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN FUNC_TAIL END*/

/*Add a number symbol.*/
static void
njs_add_number (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, RJS_Number njs_n)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_v = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_value_set_number(njs_rt, njs_v, njs_n);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_v);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add structure or union object.*/
static void
njs_add_box (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, size_t njs_size, RJS_Value *njs_proto, RJS_NativeFunc njs_constr_nf)
{
    rjs_ordinary_object_create(njs_rt, NULL, njs_proto);

    if (njs_constr_nf) {
        size_t njs_top = rjs_value_stack_save(njs_rt);
        RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
        RJS_Value *njs_constr = rjs_value_stack_push(njs_rt);
        RJS_Value *njs_sizep = rjs_value_stack_push(njs_rt);
        RJS_PropertyName njs_pn;

        rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
        rjs_create_builtin_function(njs_rt, njs_mod, njs_constr_nf, 1, njs_name, NULL, NULL, NULL, njs_constr);
        rjs_make_constructor(njs_rt, njs_constr, RJS_FALSE, njs_proto);
        rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_constr);

        rjs_string_from_chars(njs_rt, njs_name, "size", -1);
        rjs_value_set_number(njs_rt, njs_sizep, njs_size);
        rjs_property_name_init(njs_rt, &njs_pn, njs_name);
        rjs_create_data_property(njs_rt, njs_constr, &njs_pn, njs_sizep);
        rjs_property_name_deinit(njs_rt, &njs_pn);

        rjs_value_stack_restore(njs_rt, njs_top);
    } else if (!strcmp(njs_ncstr, "$")) {
        size_t njs_top = rjs_value_stack_save(njs_rt);
        RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

        rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
        rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_proto);

        rjs_value_stack_restore(njs_rt, njs_top);
    }
}

/*Add a C type.*/
static void
njs_add_ctype (RJS_Runtime *njs_rt, const char *njs_ncstr, size_t njs_size, RJS_Value *njs_proto, RJS_CType **njs_pctype)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_c_type(njs_rt, njs_name, njs_size, njs_proto, njs_pctype);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add member accessor.*/
static void
njs_add_accessor (RJS_Runtime *njs_rt, RJS_Value *njs_mod, RJS_Value *njs_proto, const char *njs_ncstr, RJS_NativeFunc njs_get, RJS_NativeFunc njs_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_builtin_accessor(njs_rt, njs_mod, njs_proto, njs_get, njs_set, njs_name, NULL);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add function.*/
static void
njs_add_func (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, RJS_NativeFunc njs_nf, size_t njs_pn)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_func = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_builtin_function(njs_rt, njs_mod, njs_nf, njs_pn, njs_name, NULL, NULL, NULL, njs_func);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_func);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Set the export symbols.*/
RJS_Result
ratjs_module_init (RJS_Runtime *njs_rt, RJS_Value *njs_mod)
{
    /*Add export entries.*/
    rjs_module_set_import_export(njs_rt, njs_mod, NULL, njs_local_exports, NULL, NULL);

/*NJSGEN MODULE_INIT BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_INIT END*/

    return RJS_OK;
}   

/*Initialize the local bindings.*/
RJS_Result
ratjs_module_exec (RJS_Runtime *njs_rt, RJS_Value *njs_mod)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_MyStruct1_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_MyStruct2_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_MyUnion_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_vars = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Initialize the module data.*/
    njs_md = malloc(sizeof(NJS_ModuleData));
    assert(njs_md);
    njs_md->ctype_MyStruct1 = NULL;
    njs_md->ctype_MyStruct2 = NULL;
    njs_md->ctype_MyUnion = NULL;
    njs_md->ctype_MyFuncType = NULL;
    njs_md->ctype_MyFuncType1 = NULL;
    rjs_value_set_undefined(njs_rt, &njs_md->str_b);
    rjs_value_set_undefined(njs_rt, &njs_md->str_return);
    rjs_value_set_undefined(njs_rt, &njs_md->str_a);
    rjs_module_set_data(njs_rt, njs_mod, njs_md, njs_module_data_scan, njs_module_data_free);
    rjs_string_from_chars(njs_rt, &njs_md->str_b, "b", -1);
    rjs_string_from_chars(njs_rt, &njs_md->str_return, "return", -1);
    rjs_string_from_chars(njs_rt, &njs_md->str_a, "a", -1);
    rjs_property_name_init(njs_rt, &njs_md->pn_b, &njs_md->str_b);
    rjs_property_name_init(njs_rt, &njs_md->pn_return, &njs_md->str_return);
    rjs_property_name_init(njs_rt, &njs_md->pn_a, &njs_md->str_a);

    /*Set number symbols.*/
    njs_add_number(njs_rt, njs_mod, "NUM_MACRO_0", NUM_MACRO_0);
    njs_add_number(njs_rt, njs_mod, "NUM_MACRO_PI", NUM_MACRO_PI);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM0_V0", MY_ENUM0_V0);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM0_V1", MY_ENUM0_V1);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM0_V2", MY_ENUM0_V2);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM1_V2", MY_ENUM1_V2);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM1_V3", MY_ENUM1_V3);
    njs_add_number(njs_rt, njs_mod, "MY_ENUM1_V4", MY_ENUM1_V4);

    /*Add box objects.*/
    njs_add_box(njs_rt, njs_mod, "MyStruct1", sizeof(MyStruct1), njs_MyStruct1_proto, njs_MyStruct1_constructor);
    njs_add_box(njs_rt, njs_mod, "MyStruct2", sizeof(MyStruct2), njs_MyStruct2_proto, njs_MyStruct2_constructor);
    njs_add_box(njs_rt, njs_mod, "MyUnion", sizeof(MyUnion), njs_MyUnion_proto, njs_MyUnion_constructor);
    njs_add_box(njs_rt, njs_mod, "$", 0, njs_vars, NULL);

    /*Add C types.*/
    njs_add_ctype(njs_rt, "MyStruct1", sizeof(MyStruct1), njs_MyStruct1_proto, &njs_md->ctype_MyStruct1);
    njs_add_ctype(njs_rt, "MyStruct2", sizeof(MyStruct2), njs_MyStruct2_proto, &njs_md->ctype_MyStruct2);
    njs_add_ctype(njs_rt, "MyUnion", sizeof(MyUnion), njs_MyUnion_proto, &njs_md->ctype_MyUnion);

    /*Add accessors.*/
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct1_proto, "u8", njs_MyStruct1_u8_get, njs_MyStruct1_u8_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct1_proto, "u16", njs_MyStruct1_u16_get, njs_MyStruct1_u16_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct1_proto, "u32", njs_MyStruct1_u32_get, njs_MyStruct1_u32_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct1_proto, "u64", njs_MyStruct1_u64_get, njs_MyStruct1_u64_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct2_proto, "s", njs_MyStruct2_s_get, njs_MyStruct2_s_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct2_proto, "u8a", njs_MyStruct2_u8a_get, njs_MyStruct2_u8a_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct2_proto, "s1a", njs_MyStruct2_s1a_get, njs_MyStruct2_s1a_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyStruct2_proto, "s1", njs_MyStruct2_s1_get, njs_MyStruct2_s1_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyUnion_proto, "u8", njs_MyUnion_u8_get, njs_MyUnion_u8_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyUnion_proto, "u16", njs_MyUnion_u16_get, njs_MyUnion_u16_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyUnion_proto, "u32", njs_MyUnion_u32_get, njs_MyUnion_u32_set);
    njs_add_accessor(njs_rt, njs_mod, njs_MyUnion_proto, "u64", njs_MyUnion_u64_get, njs_MyUnion_u64_set);
    njs_add_accessor(njs_rt, njs_mod, njs_vars, "iv", njs_iv_get, njs_iv_set);
    njs_add_accessor(njs_rt, njs_mod, njs_vars, "sv", njs_sv_get, njs_sv_set);
    njs_add_accessor(njs_rt, njs_mod, njs_vars, "csv", njs_csv_get, NULL);
    njs_add_accessor(njs_rt, njs_mod, njs_vars, "fnv", njs_fnv_get, NULL);

    /*Add function types.*/
    njs_add_func_type_MyFuncType(njs_rt, njs_mod, &njs_md->ctype_MyFuncType, njs_md);
    njs_add_func_type_MyFuncType1(njs_rt, njs_mod, &njs_md->ctype_MyFuncType1, njs_md);

    /*Add functions.*/
    njs_add_func(njs_rt, njs_mod, "MyFunc0", njs_MyFunc0_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc1", njs_MyFunc1_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc2", njs_MyFunc2_nf, 0);
    njs_add_func(njs_rt, njs_mod, "MyFunc3", njs_MyFunc3_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc4", njs_MyFunc4_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc5", njs_MyFunc5_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc6", njs_MyFunc6_nf, 1);
    njs_add_func(njs_rt, njs_mod, "MyFunc7", njs_MyFunc7_nf, 2);
    njs_add_func(njs_rt, njs_mod, "MyFunc8", njs_MyFunc8_nf, 2);
    njs_add_func(njs_rt, njs_mod, "MyFunc9", njs_MyFunc9_nf, 1);

/*NJSGEN MODULE_EXEC BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_EXEC END*/

    rjs_value_stack_restore(njs_rt, njs_top);
    return RJS_OK;
}