/**
 * Generated by njsgen
 */

/*NJSGEN INCLUDE_HEAD BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN INCLUDE_HEAD END*/
#include <string.h>
#include <stdlib.h>
#include <ratjs.h>
/*NJSGEN INCLUDE_TAIL BEGIN*/
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <arpa/inet.h>

//#include <arpa/inet.h>
/*NJSGEN INCLUDE_TAIL END*/

#define NJS_NATIVE_FUNC(n)\
    RJS_Result n (RJS_Runtime *njs_rt, RJS_Value *njs_func, RJS_Value *njs_thiz, RJS_Value *njs_args, size_t njs_argc, RJS_Value *njs_nt, RJS_Value *njs_rv)

/*NJSGEN DECL BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN DECL END*/

/*Local export symbols.*/
static const RJS_ModuleExportDesc
njs_local_exports[] = {
    {NULL, NULL, "AF_UNIX", "AF_UNIX"},
    {NULL, NULL, "AF_INET", "AF_INET"},
    {NULL, NULL, "AF_INET6", "AF_INET6"},
    {NULL, NULL, "SOCK_STREAM", "SOCK_STREAM"},
    {NULL, NULL, "SOCK_DGRAM", "SOCK_DGRAM"},
    {NULL, NULL, "SOCK_SEQPACKET", "SOCK_SEQPACKET"},
    {NULL, NULL, "sockaddr_un", "sockaddr_un"},
    {NULL, NULL, "in_addr", "in_addr"},
    {NULL, NULL, "sockaddr_in", "sockaddr_in"},
    {NULL, NULL, "in6_addr", "in6_addr"},
    {NULL, NULL, "sockaddr_in6", "sockaddr_in6"},
    {NULL, NULL, "socket", "socket"},
    {NULL, NULL, "close", "close"},
    {NULL, NULL, "connect", "connect"},
    {NULL, NULL, "bind", "bind"},
    {NULL, NULL, "listen", "listen"},
    {NULL, NULL, "accept", "accept"},
    {NULL, NULL, "read", "read"},
    {NULL, NULL, "write", "write"},
    {NULL, NULL, "htonl", "htonl"},
    {NULL, NULL, "htons", "htons"},
    {NULL, NULL, "ntohl", "ntohl"},
    {NULL, NULL, "ntohs", "ntohs"},
    {NULL, NULL, "inet_aton", "inet_aton"},
    {NULL, NULL, "inet_pton", "inet_pton"},
/*NJSGEN EXPORT_TABLE_DECL BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN EXPORT_TABLE_DECL END*/
    {NULL, NULL, NULL, NULL}
};

/*NJS module data.*/
typedef struct {
    RJS_CType *ctype_sockaddr_un;
    RJS_CType *ctype_in_addr;
    RJS_CType *ctype_sockaddr_in;
    RJS_CType *ctype_in6_addr;
    RJS_CType *ctype_sockaddr_in6;
    RJS_Value str_addrlen;
    RJS_Value str_return;
    RJS_PropertyName pn_addrlen;
    RJS_PropertyName pn_return;
/*NJSGEN MODULE_DATA_DECL BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_DECL END*/
} NJS_ModuleData;

/*Scan the referenced things in the module data.*/
static void
njs_module_data_scan (RJS_Runtime *njs_rt, void *njs_p)
{
    NJS_ModuleData *njs_md = njs_p;

    njs_md = njs_md;
    rjs_gc_scan_value(njs_rt, &njs_md->str_addrlen);
    rjs_gc_scan_value(njs_rt, &njs_md->str_return);

/*NJSGEN MODULE_DATA_SCAN BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_SCAN END*/
}

/*Free the module data.*/
static void
njs_module_data_free (RJS_Runtime *njs_rt, void *njs_p)
{
    NJS_ModuleData *njs_md = njs_p;

    rjs_property_name_deinit(njs_rt, &njs_md->pn_addrlen);
    rjs_property_name_deinit(njs_rt, &njs_md->pn_return);

/*NJSGEN MODULE_DATA_FREE BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_DATA_FREE END*/

    free(njs_md);
}

/*NJSGEN FUNC_HEAD BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN FUNC_HEAD END*/

/*Constructor of "sockaddr_un"*/
static NJS_NATIVE_FUNC(njs_sockaddr_un_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    struct sockaddr_un *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the sockaddr_un buffer.*/
    njs_cptr = malloc(sizeof(struct sockaddr_un) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(struct sockaddr_un));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_sockaddr_un, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the sockaddr_un.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_un.sun_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_un_sun_family_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_un *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_un pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_un, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sun_family".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sun_family);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_un.sun_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_un_sun_family_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_un *njs_cptr;
    RJS_Number njs_sun_family_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_un pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_un, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sun_family".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sun_family_num)) == RJS_ERR)
        goto end;
    njs_cptr->sun_family = njs_sun_family_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_un.sun_path"*/
static NJS_NATIVE_FUNC(njs_sockaddr_un_sun_path_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_un *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_un pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_un, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sun_path".*/
    if ((njs_r = rjs_string_from_enc_chars(njs_rt, njs_rv, njs_cptr->sun_path, -1, NULL)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_un.sun_path"*/
static NJS_NATIVE_FUNC(njs_sockaddr_un_sun_path_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_un *njs_cptr;
    RJS_Value *njs_sun_path_str = rjs_value_stack_push(njs_rt);
    const char *njs_sun_path_cstr;
    RJS_CharBuffer njs_sun_path_cb;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    rjs_char_buffer_init(njs_rt, &njs_sun_path_cb);

    /*Get the sockaddr_un pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_un, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sun_path".*/
    if ((njs_r = rjs_to_string(njs_rt, njs_arg, njs_sun_path_str)) == RJS_ERR)
        goto end;
    if (!(njs_sun_path_cstr = rjs_string_to_enc_chars(njs_rt, njs_sun_path_str, &njs_sun_path_cb, NULL))) {
        njs_r = RJS_ERR;
        goto end;
    }
    if (snprintf(njs_cptr->sun_path, sizeof(njs_cptr->sun_path), "%s", njs_sun_path_cstr) >= sizeof(njs_cptr->sun_path)) {
        njs_r = rjs_throw_range_error(njs_rt, "input string is too long");
        goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_char_buffer_deinit(njs_rt, &njs_sun_path_cb);
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "in_addr"*/
static NJS_NATIVE_FUNC(njs_in_addr_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    struct in_addr *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the in_addr buffer.*/
    njs_cptr = malloc(sizeof(struct in_addr) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(struct in_addr));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in_addr, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the in_addr.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "sockaddr_in"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    struct sockaddr_in *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the sockaddr_in buffer.*/
    njs_cptr = malloc(sizeof(struct sockaddr_in) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(struct sockaddr_in));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the sockaddr_in.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in.sin_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_family_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin_family".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin_family);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in.sin_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_family_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;
    RJS_Number njs_sin_family_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin_family".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin_family_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin_family = njs_sin_family_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in.sin_port"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_port_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin_port".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin_port);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in.sin_port"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_port_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;
    RJS_Number njs_sin_port_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin_port".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin_port_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin_port = njs_sin_port_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in.sin_addr"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_addr_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin_addr".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in_addr, (void*)&njs_cptr->sin_addr, RJS_CPTR_TYPE_VALUE, 1, 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in.sin_addr"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in_sin_addr_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in *njs_cptr;
    struct in_addr* njs_sin_addr_cptr;
    RJS_Value *njs_sin_addr_cptrv = rjs_value_stack_push(njs_rt);

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin_addr".*/
    if (rjs_is_c_ptr(njs_rt, njs_arg)) {
        if (!(njs_sin_addr_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_in_addr, RJS_CPTR_TYPE_VALUE, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }
        njs_cptr->sin_addr = *njs_sin_addr_cptr;
    } else {
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in_addr, &njs_cptr->sin_addr, RJS_CPTR_TYPE_VALUE, 1, 0, njs_sin_addr_cptrv)) == RJS_ERR)
            goto end;
        if ((njs_r = rjs_object_assign(njs_rt, njs_sin_addr_cptrv, njs_arg)) == RJS_ERR)
            goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "in6_addr"*/
static NJS_NATIVE_FUNC(njs_in6_addr_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    struct in6_addr *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the in6_addr buffer.*/
    njs_cptr = malloc(sizeof(struct in6_addr) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(struct in6_addr));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in6_addr, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the in6_addr.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Constructor of "sockaddr_in6"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_constructor)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    size_t njs_nitem = 1;
    RJS_Value *njs_init_obj = NULL;
    RJS_CPtrType njs_cptr_type = RJS_CPTR_TYPE_VALUE;
    int njs_cptr_flags = RJS_CPTR_FL_AUTO_FREE;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);
    if (rjs_value_is_number(njs_rt, njs_arg)) {
        /*Get the array's length.*/
        int64_t njs_len;
        if ((njs_r = rjs_to_length(njs_rt, njs_arg, &njs_len)) == RJS_ERR)
            goto end;
        njs_nitem = njs_len;
        njs_cptr_type = RJS_CPTR_TYPE_ARRAY;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    } else if (rjs_value_is_object(njs_rt, njs_arg)) {
        /*Get the initialize object.*/
        njs_init_obj = njs_arg;
        njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    }

    /*Check the automatically free flag.*/
    if (!rjs_value_is_undefined(njs_rt, njs_arg)) {
        if (!rjs_to_boolean(njs_rt, njs_arg))
            njs_cptr_flags &= ~RJS_CPTR_FL_AUTO_FREE;
    }

    /*Allocate the sockaddr_in6 buffer.*/
    njs_cptr = malloc(sizeof(struct sockaddr_in6) * njs_nitem);
    if (!njs_cptr) {
        njs_r = rjs_throw_range_error(njs_rt, "cannot allocate enough memory");
        goto end;
    }
    memset(njs_cptr, 0, njs_nitem * sizeof(struct sockaddr_in6));

    /*Create the C pointer object.*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, njs_cptr, njs_cptr_type, njs_nitem, njs_cptr_flags, njs_rv)) == RJS_ERR)
        goto end;

    /*Initialize the sockaddr_in6.*/
    if (njs_init_obj) {
        if ((njs_r = rjs_object_assign(njs_rt, njs_rv, njs_init_obj)) == RJS_ERR)
            goto end;
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in6.sin6_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_family_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin6_family".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin6_family);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in6.sin6_family"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_family_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;
    RJS_Number njs_sin6_family_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin6_family".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin6_family_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin6_family = njs_sin6_family_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in6.sin6_port"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_port_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin6_port".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin6_port);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in6.sin6_port"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_port_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;
    RJS_Number njs_sin6_port_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin6_port".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin6_port_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin6_port = njs_sin6_port_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in6.sin6_flowinfo"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_flowinfo_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin6_flowinfo".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin6_flowinfo);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in6.sin6_flowinfo"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_flowinfo_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;
    RJS_Number njs_sin6_flowinfo_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin6_flowinfo".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin6_flowinfo_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin6_flowinfo = njs_sin6_flowinfo_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in6.sin6_addr"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_addr_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin6_addr".*/
    if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in6_addr, (void*)&njs_cptr->sin6_addr, RJS_CPTR_TYPE_VALUE, 1, 0, njs_rv)) == RJS_ERR)
        goto end;

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in6.sin6_addr"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_addr_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;
    struct in6_addr* njs_sin6_addr_cptr;
    RJS_Value *njs_sin6_addr_cptrv = rjs_value_stack_push(njs_rt);

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin6_addr".*/
    if (rjs_is_c_ptr(njs_rt, njs_arg)) {
        if (!(njs_sin6_addr_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_in6_addr, RJS_CPTR_TYPE_VALUE, njs_arg))) {
            njs_r = RJS_ERR;
            goto end;
        }
        njs_cptr->sin6_addr = *njs_sin6_addr_cptr;
    } else {
        if ((njs_r = rjs_create_c_ptr(njs_rt, njs_md->ctype_in6_addr, &njs_cptr->sin6_addr, RJS_CPTR_TYPE_VALUE, 1, 0, njs_sin6_addr_cptrv)) == RJS_ERR)
            goto end;
        if ((njs_r = rjs_object_assign(njs_rt, njs_sin6_addr_cptrv, njs_arg)) == RJS_ERR)
            goto end;
    }

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Getter of "sockaddr_in6.sin6_scope_id"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_scope_id_get)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Get "sin6_scope_id".*/
    rjs_value_set_number(njs_rt, njs_rv, njs_cptr->sin6_scope_id);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Setter of "sockaddr_in6.sin6_scope_id"*/
static NJS_NATIVE_FUNC(njs_sockaddr_in6_sin6_scope_id_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    RJS_Value *njs_arg = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    struct sockaddr_in6 *njs_cptr;
    RJS_Number njs_sin6_scope_id_num;

    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Get the sockaddr_in6 pointer.*/
    if (!(njs_cptr = rjs_get_c_ptr(njs_rt, njs_md->ctype_sockaddr_in6, RJS_CPTR_TYPE_VALUE, njs_thiz))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Set "sin6_scope_id".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg, &njs_sin6_scope_id_num)) == RJS_ERR)
        goto end;
    njs_cptr->sin6_scope_id = njs_sin6_scope_id_num;

    rjs_value_set_undefined(njs_rt, njs_rv);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "socket"*/
static NJS_NATIVE_FUNC(njs_socket_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_domain;
    RJS_Value *njs_arg_v_domain = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_domain_num;
    int njs_arg_type;
    RJS_Value *njs_arg_v_type = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Number njs_type_num;
    int njs_arg_protocal;
    RJS_Value *njs_arg_v_protocal = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    RJS_Number njs_protocal_num;
    int njs_ret;

    /*Convert input parameter "domain".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_domain, &njs_domain_num)) == RJS_ERR)
        goto end;
    njs_arg_domain = njs_domain_num;
    /*Convert input parameter "type".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_type, &njs_type_num)) == RJS_ERR)
        goto end;
    njs_arg_type = njs_type_num;
    /*Convert input parameter "protocal".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_protocal, &njs_protocal_num)) == RJS_ERR)
        goto end;
    njs_arg_protocal = njs_protocal_num;

    /*Call "socket".*/
    njs_ret = socket(njs_arg_domain, njs_arg_type, njs_arg_protocal);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "close"*/
static NJS_NATIVE_FUNC(njs_close_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_sockfd;
    RJS_Value *njs_arg_v_sockfd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_sockfd_num;
    int njs_ret;

    /*Convert input parameter "sockfd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_sockfd, &njs_sockfd_num)) == RJS_ERR)
        goto end;
    njs_arg_sockfd = njs_sockfd_num;

    /*Call "close".*/
    njs_ret = close(njs_arg_sockfd);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "connect"*/
static NJS_NATIVE_FUNC(njs_connect_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_sockfd;
    RJS_Value *njs_arg_v_sockfd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_sockfd_num;
    const void* njs_arg_addr;
    RJS_Value *njs_arg_v_addr = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    int njs_arg_addrlen;
    RJS_Value *njs_arg_v_addrlen = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    RJS_Number njs_addrlen_num;
    int njs_ret;

    /*Convert input parameter "sockfd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_sockfd, &njs_sockfd_num)) == RJS_ERR)
        goto end;
    njs_arg_sockfd = njs_sockfd_num;
    /*Convert input parameter "addr".*/
    if (!(njs_arg_addr = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_addr))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "addrlen".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_addrlen, &njs_addrlen_num)) == RJS_ERR)
        goto end;
    njs_arg_addrlen = njs_addrlen_num;

    /*Call "connect".*/
    njs_ret = connect(njs_arg_sockfd, njs_arg_addr, njs_arg_addrlen);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "bind"*/
static NJS_NATIVE_FUNC(njs_bind_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_sockfd;
    RJS_Value *njs_arg_v_sockfd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_sockfd_num;
    const void* njs_arg_addr;
    RJS_Value *njs_arg_v_addr = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    int njs_arg_addrlen;
    RJS_Value *njs_arg_v_addrlen = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    RJS_Number njs_addrlen_num;
    int njs_ret;

    /*Convert input parameter "sockfd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_sockfd, &njs_sockfd_num)) == RJS_ERR)
        goto end;
    njs_arg_sockfd = njs_sockfd_num;
    /*Convert input parameter "addr".*/
    if (!(njs_arg_addr = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_addr))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "addrlen".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_addrlen, &njs_addrlen_num)) == RJS_ERR)
        goto end;
    njs_arg_addrlen = njs_addrlen_num;

    /*Call "bind".*/
    njs_ret = bind(njs_arg_sockfd, njs_arg_addr, njs_arg_addrlen);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "listen"*/
static NJS_NATIVE_FUNC(njs_listen_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_sockfd;
    RJS_Value *njs_arg_v_sockfd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_sockfd_num;
    int njs_arg_backlog;
    RJS_Value *njs_arg_v_backlog = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Number njs_backlog_num;
    int njs_ret;

    /*Convert input parameter "sockfd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_sockfd, &njs_sockfd_num)) == RJS_ERR)
        goto end;
    njs_arg_sockfd = njs_sockfd_num;
    /*Convert input parameter "backlog".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_backlog, &njs_backlog_num)) == RJS_ERR)
        goto end;
    njs_arg_backlog = njs_backlog_num;

    /*Call "listen".*/
    njs_ret = listen(njs_arg_sockfd, njs_arg_backlog);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "accept"*/
static NJS_NATIVE_FUNC(njs_accept_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_sockfd;
    RJS_Value *njs_arg_v_sockfd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_sockfd_num;
    void* njs_arg_addr;
    RJS_Value *njs_arg_v_addr = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    uint32_t* njs_arg_addrlen;
    uint32_t njs_arg_d_addrlen;
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    int njs_ret;
    RJS_Value *njs_ret_p = rjs_value_stack_push(njs_rt);

    njs_arg_addrlen = &njs_arg_d_addrlen;
    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "sockfd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_sockfd, &njs_sockfd_num)) == RJS_ERR)
        goto end;
    njs_arg_sockfd = njs_sockfd_num;
    /*Convert input parameter "addr".*/
    if (!(njs_arg_addr = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_addr))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Call "accept".*/
    njs_ret = accept(njs_arg_sockfd, njs_arg_addr, njs_arg_addrlen);
    /*Create return object.*/
    rjs_ordinary_object_create(njs_rt, NULL, njs_rv);

    /*Convert the output parameter "addrlen".*/
    rjs_value_set_number(njs_rt, njs_ret_p, njs_arg_d_addrlen);
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_addrlen, njs_ret_p);
    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_ret_p, njs_ret);
    }
    rjs_create_data_property_or_throw(njs_rt, njs_rv, &njs_md->pn_return, njs_ret_p);

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "read"*/
static NJS_NATIVE_FUNC(njs_read_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_fd;
    RJS_Value *njs_arg_v_fd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_fd_num;
    void* njs_arg_buf;
    RJS_Value *njs_arg_v_buf = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    size_t njs_arg_count;
    RJS_Value *njs_arg_v_count = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    RJS_Number njs_count_num;
    ssize_t njs_ret;

    /*Convert input parameter "fd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_fd, &njs_fd_num)) == RJS_ERR)
        goto end;
    njs_arg_fd = njs_fd_num;
    /*Convert input parameter "buf".*/
    if (!(njs_arg_buf = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_buf))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "count".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_count, &njs_count_num)) == RJS_ERR)
        goto end;
    njs_arg_count = njs_count_num;

    /*Call "read".*/
    njs_ret = read(njs_arg_fd, njs_arg_buf, njs_arg_count);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "write"*/
static NJS_NATIVE_FUNC(njs_write_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_fd;
    RJS_Value *njs_arg_v_fd = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_fd_num;
    void* njs_arg_buf;
    RJS_Value *njs_arg_v_buf = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    size_t njs_arg_count;
    RJS_Value *njs_arg_v_count = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    RJS_Number njs_count_num;
    ssize_t njs_ret;

    /*Convert input parameter "fd".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_fd, &njs_fd_num)) == RJS_ERR)
        goto end;
    njs_arg_fd = njs_fd_num;
    /*Convert input parameter "buf".*/
    if (!(njs_arg_buf = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_buf))) {
        njs_r = RJS_ERR;
        goto end;
    }
    /*Convert input parameter "count".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_count, &njs_count_num)) == RJS_ERR)
        goto end;
    njs_arg_count = njs_count_num;

    /*Call "write".*/
    njs_ret = write(njs_arg_fd, njs_arg_buf, njs_arg_count);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "htonl"*/
static NJS_NATIVE_FUNC(njs_htonl_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    uint32_t njs_arg_hostlong;
    RJS_Value *njs_arg_v_hostlong = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_hostlong_num;
    uint32_t njs_ret;

    /*Convert input parameter "hostlong".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_hostlong, &njs_hostlong_num)) == RJS_ERR)
        goto end;
    njs_arg_hostlong = njs_hostlong_num;

    /*Call "htonl".*/
    njs_ret = htonl(njs_arg_hostlong);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "htons"*/
static NJS_NATIVE_FUNC(njs_htons_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    uint16_t njs_arg_hostshort;
    RJS_Value *njs_arg_v_hostshort = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_hostshort_num;
    uint16_t njs_ret;

    /*Convert input parameter "hostshort".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_hostshort, &njs_hostshort_num)) == RJS_ERR)
        goto end;
    njs_arg_hostshort = njs_hostshort_num;

    /*Call "htons".*/
    njs_ret = htons(njs_arg_hostshort);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "ntohl"*/
static NJS_NATIVE_FUNC(njs_ntohl_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    uint32_t njs_arg_netlong;
    RJS_Value *njs_arg_v_netlong = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_netlong_num;
    uint32_t njs_ret;

    /*Convert input parameter "netlong".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_netlong, &njs_netlong_num)) == RJS_ERR)
        goto end;
    njs_arg_netlong = njs_netlong_num;

    /*Call "ntohl".*/
    njs_ret = ntohl(njs_arg_netlong);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "ntohs"*/
static NJS_NATIVE_FUNC(njs_ntohs_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    uint16_t njs_arg_netshort;
    RJS_Value *njs_arg_v_netshort = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_netshort_num;
    uint16_t njs_ret;

    /*Convert input parameter "netshort".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_netshort, &njs_netshort_num)) == RJS_ERR)
        goto end;
    njs_arg_netshort = njs_netshort_num;

    /*Call "ntohs".*/
    njs_ret = ntohs(njs_arg_netshort);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "inet_aton"*/
static NJS_NATIVE_FUNC(njs_inet_aton_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    const char* njs_arg_cp;
    RJS_Value *njs_arg_v_cp = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Value *njs_cp_str = rjs_value_stack_push(njs_rt);
    RJS_CharBuffer njs_cp_cb;
    struct in_addr* njs_arg_inp;
    RJS_Value *njs_arg_v_inp = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Value *njs_mod = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;
    int njs_ret;

    rjs_char_buffer_init(njs_rt, &njs_cp_cb);
    /*Get module data.*/
    rjs_get_function_module(njs_rt, njs_func, njs_mod);
    njs_md = rjs_module_get_data(njs_rt, njs_mod);

    /*Convert input parameter "cp".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_cp) || rjs_value_is_undefined(njs_rt, njs_arg_v_cp)) {
        njs_arg_cp = NULL;
    } else {
        if ((njs_r = rjs_to_string(njs_rt, njs_arg_v_cp, njs_cp_str)) == RJS_ERR)
            goto end;
        if (!(njs_arg_cp = rjs_string_to_enc_chars(njs_rt, njs_cp_str, &njs_cp_cb, NULL))) {
            njs_r = RJS_ERR;
            goto end;
        }
    }
    /*Convert input parameter "inp".*/
    if (!(njs_arg_inp = rjs_get_c_ptr(njs_rt, njs_md->ctype_in_addr, RJS_CPTR_TYPE_VALUE, njs_arg_v_inp))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Call "inet_aton".*/
    njs_ret = inet_aton(njs_arg_cp, njs_arg_inp);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_char_buffer_deinit(njs_rt, &njs_cp_cb);
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*Wrapper of "inet_pton"*/
static NJS_NATIVE_FUNC(njs_inet_pton_nf)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Result njs_r;
    int njs_arg_af;
    RJS_Value *njs_arg_v_af = rjs_argument_get(njs_rt, njs_args, njs_argc, 0);
    RJS_Number njs_af_num;
    const char* njs_arg_src;
    RJS_Value *njs_arg_v_src = rjs_argument_get(njs_rt, njs_args, njs_argc, 1);
    RJS_Value *njs_src_str = rjs_value_stack_push(njs_rt);
    RJS_CharBuffer njs_src_cb;
    void* njs_arg_dst;
    RJS_Value *njs_arg_v_dst = rjs_argument_get(njs_rt, njs_args, njs_argc, 2);
    int njs_ret;

    rjs_char_buffer_init(njs_rt, &njs_src_cb);

    /*Convert input parameter "af".*/
    if ((njs_r = rjs_to_number(njs_rt, njs_arg_v_af, &njs_af_num)) == RJS_ERR)
        goto end;
    njs_arg_af = njs_af_num;
    /*Convert input parameter "src".*/
    if (rjs_value_is_null(njs_rt, njs_arg_v_src) || rjs_value_is_undefined(njs_rt, njs_arg_v_src)) {
        njs_arg_src = NULL;
    } else {
        if ((njs_r = rjs_to_string(njs_rt, njs_arg_v_src, njs_src_str)) == RJS_ERR)
            goto end;
        if (!(njs_arg_src = rjs_string_to_enc_chars(njs_rt, njs_src_str, &njs_src_cb, NULL))) {
            njs_r = RJS_ERR;
            goto end;
        }
    }
    /*Convert input parameter "dst".*/
    if (!(njs_arg_dst = rjs_get_c_ptr(njs_rt, NULL, RJS_CPTR_TYPE_UNKNOWN, njs_arg_v_dst))) {
        njs_r = RJS_ERR;
        goto end;
    }

    /*Call "inet_pton".*/
    njs_ret = inet_pton(njs_arg_af, njs_arg_src, njs_arg_dst);

    /*Convert the return value.*/
    {
    rjs_value_set_number(njs_rt, njs_rv, njs_ret);
    }

    njs_r = RJS_OK;
    goto end;
end:
    rjs_char_buffer_deinit(njs_rt, &njs_src_cb);
    rjs_value_stack_restore(njs_rt, njs_top);
    return njs_r;
}

/*NJSGEN FUNC_TAIL BEGIN*/
/*NJSGEN TODO*/
/*NJSGEN FUNC_TAIL END*/

/*Add a number symbol.*/
static void
njs_add_number (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, RJS_Number njs_n)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_v = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_value_set_number(njs_rt, njs_v, njs_n);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_v);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add structure or union object.*/
static void
njs_add_box (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, size_t njs_size, RJS_Value *njs_proto, RJS_NativeFunc njs_constr_nf)
{
    rjs_ordinary_object_create(njs_rt, NULL, njs_proto);

    if (njs_constr_nf) {
        size_t njs_top = rjs_value_stack_save(njs_rt);
        RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
        RJS_Value *njs_constr = rjs_value_stack_push(njs_rt);
        RJS_Value *njs_sizep = rjs_value_stack_push(njs_rt);
        RJS_PropertyName njs_pn;

        rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
        rjs_create_builtin_function(njs_rt, njs_mod, njs_constr_nf, 1, njs_name, NULL, NULL, NULL, njs_constr);
        rjs_make_constructor(njs_rt, njs_constr, RJS_FALSE, njs_proto);
        rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_constr);

        rjs_string_from_chars(njs_rt, njs_name, "size", -1);
        rjs_value_set_number(njs_rt, njs_sizep, njs_size);
        rjs_property_name_init(njs_rt, &njs_pn, njs_name);
        rjs_create_data_property(njs_rt, njs_constr, &njs_pn, njs_sizep);
        rjs_property_name_deinit(njs_rt, &njs_pn);

        rjs_value_stack_restore(njs_rt, njs_top);
    } else if (!strcmp(njs_ncstr, "$")) {
        size_t njs_top = rjs_value_stack_save(njs_rt);
        RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

        rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
        rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_proto);

        rjs_value_stack_restore(njs_rt, njs_top);
    }
}

/*Add a C type.*/
static void
njs_add_ctype (RJS_Runtime *njs_rt, const char *njs_ncstr, size_t njs_size, RJS_Value *njs_proto, RJS_CType **njs_pctype)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_c_type(njs_rt, njs_name, njs_size, njs_proto, njs_pctype);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add member accessor.*/
static void
njs_add_accessor (RJS_Runtime *njs_rt, RJS_Value *njs_mod, RJS_Value *njs_proto, const char *njs_ncstr, RJS_NativeFunc njs_get, RJS_NativeFunc njs_set)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_builtin_accessor(njs_rt, njs_mod, njs_proto, njs_get, njs_set, njs_name, NULL);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Add function.*/
static void
njs_add_func (RJS_Runtime *njs_rt, RJS_Value *njs_mod, const char *njs_ncstr, RJS_NativeFunc njs_nf, size_t njs_pn)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_name = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_func = rjs_value_stack_push(njs_rt);

    rjs_string_from_chars(njs_rt, njs_name, njs_ncstr, -1);
    rjs_create_builtin_function(njs_rt, njs_mod, njs_nf, njs_pn, njs_name, NULL, NULL, NULL, njs_func);
    rjs_module_add_binding(njs_rt, njs_mod, njs_name, njs_func);

    rjs_value_stack_restore(njs_rt, njs_top);
}

/*Set the export symbols.*/
RJS_Result
ratjs_module_init (RJS_Runtime *njs_rt, RJS_Value *njs_mod)
{
    /*Add export entries.*/
    rjs_module_set_import_export(njs_rt, njs_mod, NULL, njs_local_exports, NULL, NULL);

/*NJSGEN MODULE_INIT BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_INIT END*/

    return RJS_OK;
}   

/*Initialize the local bindings.*/
RJS_Result
ratjs_module_exec (RJS_Runtime *njs_rt, RJS_Value *njs_mod)
{
    size_t njs_top = rjs_value_stack_save(njs_rt);
    RJS_Value *njs_sockaddr_un_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_in_addr_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_sockaddr_in_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_in6_addr_proto = rjs_value_stack_push(njs_rt);
    RJS_Value *njs_sockaddr_in6_proto = rjs_value_stack_push(njs_rt);
    NJS_ModuleData *njs_md;

    /*Initialize the module data.*/
    njs_md = malloc(sizeof(NJS_ModuleData));
    assert(njs_md);
    njs_md->ctype_sockaddr_un = NULL;
    njs_md->ctype_in_addr = NULL;
    njs_md->ctype_sockaddr_in = NULL;
    njs_md->ctype_in6_addr = NULL;
    njs_md->ctype_sockaddr_in6 = NULL;
    rjs_value_set_undefined(njs_rt, &njs_md->str_addrlen);
    rjs_value_set_undefined(njs_rt, &njs_md->str_return);
    rjs_module_set_data(njs_rt, njs_mod, njs_md, njs_module_data_scan, njs_module_data_free);
    rjs_string_from_chars(njs_rt, &njs_md->str_addrlen, "addrlen", -1);
    rjs_string_from_chars(njs_rt, &njs_md->str_return, "return", -1);
    rjs_property_name_init(njs_rt, &njs_md->pn_addrlen, &njs_md->str_addrlen);
    rjs_property_name_init(njs_rt, &njs_md->pn_return, &njs_md->str_return);

    /*Set number symbols.*/
    njs_add_number(njs_rt, njs_mod, "AF_UNIX", AF_UNIX);
    njs_add_number(njs_rt, njs_mod, "AF_INET", AF_INET);
    njs_add_number(njs_rt, njs_mod, "AF_INET6", AF_INET6);
    njs_add_number(njs_rt, njs_mod, "SOCK_STREAM", SOCK_STREAM);
    njs_add_number(njs_rt, njs_mod, "SOCK_DGRAM", SOCK_DGRAM);
    njs_add_number(njs_rt, njs_mod, "SOCK_SEQPACKET", SOCK_SEQPACKET);

    /*Add box objects.*/
    njs_add_box(njs_rt, njs_mod, "sockaddr_un", sizeof(struct sockaddr_un), njs_sockaddr_un_proto, njs_sockaddr_un_constructor);
    njs_add_box(njs_rt, njs_mod, "in_addr", sizeof(struct in_addr), njs_in_addr_proto, njs_in_addr_constructor);
    njs_add_box(njs_rt, njs_mod, "sockaddr_in", sizeof(struct sockaddr_in), njs_sockaddr_in_proto, njs_sockaddr_in_constructor);
    njs_add_box(njs_rt, njs_mod, "in6_addr", sizeof(struct in6_addr), njs_in6_addr_proto, njs_in6_addr_constructor);
    njs_add_box(njs_rt, njs_mod, "sockaddr_in6", sizeof(struct sockaddr_in6), njs_sockaddr_in6_proto, njs_sockaddr_in6_constructor);

    /*Add C types.*/
    njs_add_ctype(njs_rt, "sockaddr_un", sizeof(struct sockaddr_un), njs_sockaddr_un_proto, &njs_md->ctype_sockaddr_un);
    njs_add_ctype(njs_rt, "in_addr", sizeof(struct in_addr), njs_in_addr_proto, &njs_md->ctype_in_addr);
    njs_add_ctype(njs_rt, "sockaddr_in", sizeof(struct sockaddr_in), njs_sockaddr_in_proto, &njs_md->ctype_sockaddr_in);
    njs_add_ctype(njs_rt, "in6_addr", sizeof(struct in6_addr), njs_in6_addr_proto, &njs_md->ctype_in6_addr);
    njs_add_ctype(njs_rt, "sockaddr_in6", sizeof(struct sockaddr_in6), njs_sockaddr_in6_proto, &njs_md->ctype_sockaddr_in6);

    /*Add accessors.*/
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_un_proto, "sun_family", njs_sockaddr_un_sun_family_get, njs_sockaddr_un_sun_family_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_un_proto, "sun_path", njs_sockaddr_un_sun_path_get, njs_sockaddr_un_sun_path_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in_proto, "sin_family", njs_sockaddr_in_sin_family_get, njs_sockaddr_in_sin_family_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in_proto, "sin_port", njs_sockaddr_in_sin_port_get, njs_sockaddr_in_sin_port_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in_proto, "sin_addr", njs_sockaddr_in_sin_addr_get, njs_sockaddr_in_sin_addr_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in6_proto, "sin6_family", njs_sockaddr_in6_sin6_family_get, njs_sockaddr_in6_sin6_family_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in6_proto, "sin6_port", njs_sockaddr_in6_sin6_port_get, njs_sockaddr_in6_sin6_port_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in6_proto, "sin6_flowinfo", njs_sockaddr_in6_sin6_flowinfo_get, njs_sockaddr_in6_sin6_flowinfo_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in6_proto, "sin6_addr", njs_sockaddr_in6_sin6_addr_get, njs_sockaddr_in6_sin6_addr_set);
    njs_add_accessor(njs_rt, njs_mod, njs_sockaddr_in6_proto, "sin6_scope_id", njs_sockaddr_in6_sin6_scope_id_get, njs_sockaddr_in6_sin6_scope_id_set);

    /*Add function types.*/

    /*Add functions.*/
    njs_add_func(njs_rt, njs_mod, "socket", njs_socket_nf, 3);
    njs_add_func(njs_rt, njs_mod, "close", njs_close_nf, 1);
    njs_add_func(njs_rt, njs_mod, "connect", njs_connect_nf, 3);
    njs_add_func(njs_rt, njs_mod, "bind", njs_bind_nf, 3);
    njs_add_func(njs_rt, njs_mod, "listen", njs_listen_nf, 2);
    njs_add_func(njs_rt, njs_mod, "accept", njs_accept_nf, 3);
    njs_add_func(njs_rt, njs_mod, "read", njs_read_nf, 3);
    njs_add_func(njs_rt, njs_mod, "write", njs_write_nf, 3);
    njs_add_func(njs_rt, njs_mod, "htonl", njs_htonl_nf, 1);
    njs_add_func(njs_rt, njs_mod, "htons", njs_htons_nf, 1);
    njs_add_func(njs_rt, njs_mod, "ntohl", njs_ntohl_nf, 1);
    njs_add_func(njs_rt, njs_mod, "ntohs", njs_ntohs_nf, 1);
    njs_add_func(njs_rt, njs_mod, "inet_aton", njs_inet_aton_nf, 2);
    njs_add_func(njs_rt, njs_mod, "inet_pton", njs_inet_pton_nf, 3);

/*NJSGEN MODULE_EXEC BEGIN*/
    /*NJSGEN TODO*/
/*NJSGEN MODULE_EXEC END*/

    rjs_value_stack_restore(njs_rt, njs_top);
    return RJS_OK;
}